### ISSUE TITLE
Victims: Report a Missing Person

### ISSUE THREAD

**Issue by thatfiredev** [mozdevz/idai.africa#3]
When the user clicks on the option "Report a Missing Person" from the Landing Page, it should redirect them to a screen where they can search in our database.
If they find the missing person, they should see the "Existing Victim Profile". If not, they should be able to "Create New Victim Profile".

![Screenshot from 2019-03-29 13-36-07](https://user-images.githubusercontent.com/16766726/55230261-ee7ecb80-5227-11e9-908c-d9579a57a466.png)

**Comment by thatfiredev** [comment]
After spending Saturday morning brainstorming with some people from World Bank who work with Disaster Management, we have decided to narrow down our platform and focus only on the "Volunteers" features. Therefore, this issue is no longer valid.

**Comment by joseseie** [comment]
I agree.
