### ISSUE TITLE
Victims: Report people in need of help

### ISSUE THREAD

**Issue by thatfiredev** [mozdevz/idai.africa#4]
When the user clicks on the option "Report people in need of help" from the Landing Page, it should redirect them to a screen where they can open a report in our platform. This report will then be shown on the map.

![Screenshot from 2019-03-29 13-40-15](https://user-images.githubusercontent.com/16766726/55230356-4584a080-5228-11e9-995b-07447a18c6c0.png)

**Comment by thatfiredev** [comment]
After spending Saturday morning brainstorming with some people from World Bank who work with Disaster Management, we have decided to narrow down our platform and focus only on the "Volunteers" features. Therefore, this issue is no longer valid.

**Comment by joseseie** [comment]
Ok.
